job('First-Maven-Project-Via-DSL'){
    description("First Maven job generated by DSL on ${ne Date()}, the project is a small Java application hosted on Github")
    scm {
        git("https://github.com/anshulc55/Jenkins_Upgradev3.git", master)
    }
    trigger {
        scm('H * * * *')
     }
    steps {
        maven('clean package', 'maven-samples/single-module/pom.xml')
    }
    publishers {
        // archive the generated war file
        archiveArtifacts '**/*.jar'
    }

}